### ISSUE TITLE
environment requirement (tensorflow+cuda+cudnn)

### ISSUE THREAD

**Issue by OSU-Haolin** [ykotseruba/PedestrianActionBenchmark#1]
Hi! Yulia,

I met the problem in the environment configuration. Could you tell me the exact version of CUDA and Cudnn you use in your PCPA model's training process? I used TF2.1+CUDAtoolkit10.1+Cudnn7.6.5 but meet the unknown problem of initialization of Cudnn.  Btw, I used Anaconda rather than Docker. Is there anything I need to take care of?

Thanks,
Haolin

**Comment by ykotseruba** [comment]
Hi Haolin,
The docker image we are using is tensorflow/tensorflow:2.1.0-gpu-py3 which in turn uses CUDA 10.1 and  CUDNN 7.6.4 (according to [this](https://hub.docker.com/layers/tensorflow/tensorflow/2.1.0-gpu-py3/images/sha256-1010e051dde4a9b62532a80f4a9a619013eafc78491542d5ef5da796cc2697ae?context=explore)). Unfortunately, I am not familiar with Anaconda, hopefully updating the CuDNN version will fix the issue.
Best,
Yulia

**Comment by OSU-Haolin** [comment]
> Hi Haolin,
> The docker image we are using is tensorflow/tensorflow:2.1.0-gpu-py3 which in turn uses CUDA 10.1 and CUDNN 7.6.4 (according to [this](https://hub.docker.com/layers/tensorflow/tensorflow/2.1.0-gpu-py3/images/sha256-1010e051dde4a9b62532a80f4a9a619013eafc78491542d5ef5da796cc2697ae?context=explore)). Unfortunately, I am not familiar with Anaconda, hopefully updating the CuDNN version will fix the issue.
> Best,
> Yulia

Solved. Thanks!
