### ISSUE TITLE
Request: pre-trained models

### ISSUE THREAD

**Issue by JosephGesnouin** [ykotseruba/PedestrianActionBenchmark#11]
Hello,

Would it be possible to put a zip file with all the pretrained models evaluated on the paper?
Thank you very much :)

**Comment by ykotseruba** [comment]
Hi @JosephGesnouin , 
Unfortunately, we cannot host all pretrained models and their variations for all 3 datasets. We provided the results for the default setup in the paper, however if the setup you plan to use is different then the configuration fils are a good starting point to retrain the models.
