### ISSUE TITLE
Having Troubles Training TwoStream ATGC

### ISSUE THREAD

**Issue by PaulAdamastor** [ykotseruba/PedestrianActionBenchmark#12]
Hello,

thank you for the nice code and benchmark!
I've tried running a few training but I have issues with some models:

ATGC and TwoStream both give me the error: 
"'walking': data_raw['actions'].copy(),
KeyError: 'actions'"

Could you help me with that?

And I didn't really understand how to use optical flow with I3D, could you provide me a config file?

Best regards,

**Comment by ykotseruba** [comment]
Hi @PaulAdamastor,
Thank you for your interest in our work.

I'm not getting this error when I run the code of both models. Are you using the latest annotations and data loading functions (`pie_data.py` and `jaad_data.py`)?

To use I3D with the optical flow you can modify the C3D config as follows: change the `model` to `I3D` and `obs_input_type`  to `[local_context_flow]`.  Any type with visual features should work if you append `_flow` to it. 
However, the code expects the optical flow to be precomputed. We used [FlowNet2](https://github.com/lmb-freiburg/flownet2).

**Comment by aoteman233** [comment]
> Hi @PaulAdamastor, Thank you for your interest in our work.
> 
> I'm not getting this error when I run the code of both models. Are you using the latest annotations and data loading functions (`pie_data.py` and `jaad_data.py`)?
> 
> To use I3D with the optical flow you can modify the C3D config as follows: change the `model` to `I3D` and `obs_input_type` to `[local_context_flow]`. Any type with visual features should work if you append `_flow` to it. However, the code expects the optical flow to be precomputed. We used [FlowNet2](https://github.com/lmb-freiburg/flownet2).

hello
Thank you for your excellent work
When I use I3D, the error is as follows：FileNotFoundError: [Errno 2] No such file or directory:'JAAD/optical_flow/video_0001/00522.flo'
According to your reply, what I understand is to use flownet to generate .flo files for JAAD first, and then use I3D.yaml for training. Am I right?But I don't quite understand how to use flownet to generate the optical flow file of JAAD, can you explain in more detail?
thank you very much
