### ISSUE TITLE
some errors about docker

### ISSUE THREAD

**Issue by yuchen2199** [ykotseruba/PedestrianActionBenchmark#14]
hi！I meet a puzzle problem when I run docker/build_docker.sh. Could you give me some help? thanks!
![1638593578552](https://user-images.githubusercontent.com/50839299/144697605-a526e357-db59-4f45-a228-318a17568211.png)

**Comment by ykotseruba** [comment]
Hi,
I wasn't able to reproduce this error on my machine. Is this the full error message?
One thing to try is this: remove `python-opencv` and `python-matplotlib` from apt-get in `dockers/Dockerfile_tf2` and add them to `docker/requirements.txt` to be installed using pip.
Please let me know if it solves the issue.

**Comment by yuchen2199** [comment]
This may be caused by a problem with sources, but I re-implemented it.  Thanks for your reply.

**Comment by MoritzLennartz** [comment]
hello, 

I have the same problem as yuchen2199. 

However, the suggestion to remove python-opencv and python-matplotlib from apt-get in dockers/Dockerfile_tf2 and add them to docker/requirements.txt leads to a new error

How did you solve the problem?

<img width="667" alt="image" src="https://user-images.githubusercontent.com/64199570/163323675-48c57846-d5e7-4c4e-ab27-d585082a331e.png">
