### ISSUE TITLE
Which TensorFlow and python version did you use ?

### ISSUE THREAD

**Issue by jinxing94** [ykotseruba/PedestrianActionBenchmark#16]
In your docker file, it shows
FROM tensorflow/tensorflow:latest-gpu

**Comment by ykotseruba** [comment]
This question has been answered, please see [issue #1](https://github.com/ykotseruba/PedestrianActionBenchmark/issues/1)
Python version above 3.6 should be ok

**Comment by jinxing94** [comment]
I tried tensorflow=2.1.0, but get ValueError: The `batch_size` argument must not be specified for the given input type. Received input: <action_predict.DataGenerator object at 0x7efd0811a590>, batch_size: 32.
