### ISSUE TITLE
about i3d

### ISSUE THREAD

**Issue by aoteman233** [ykotseruba/PedestrianActionBenchmark#18]
Hi @PaulAdamastor,
Thank you for your interest in our work.

I'm not getting this error when I run the code of both models. Are you using the latest annotations and data loading functions (`pie_data.py` and `jaad_data.py`)?

To use I3D with the optical flow you can modify the C3D config as follows: change the `model` to `I3D` and `obs_input_type`  to `[local_context_flow]`.  Any type with visual features should work if you append `_flow` to it. 
However, the code expects the optical flow to be precomputed. We used [FlowNet2](https://github.com/lmb-freiburg/flownet2).

_Originally posted by @ykotseruba in https://github.com/ykotseruba/PedestrianActionBenchmark/issues/12#issuecomment-910346083_

**Comment by aoteman233** [comment]
Thank you for your excellent work！
When I run the code I have two problems：
1.Did you get the following error when you used flownet2 to generate optical flow？How did you solve this problem?
   NameError: name 'validation_loader' is not defined
2.How much storage space is required for the final generated optical flow file？
Looking forward to your reply

**Comment by ykotseruba** [comment]
1. I ran this code a while ago and did not have any issues. Perhaps it is better to ask the maintainers of flownet2.
2. I don't have the exact number, but I recommend computing the optical flow only for the observed frames, not for the entire dataset. Once you extracted the data for training and testing you can save the frame ids and compute the optical flow only for those.

**Comment by aoteman233** [comment]
Thank you very much for your reply！
unfortunately I didn't see your reply until after generating all the optical flow files, it took me a lot of time, obviously I'm a noob. I will try to do as you say。
thanks again for your reply！

**Comment by aoteman233** [comment]
excuse me，I have successfully completed the training these days, but I can't find a way to extract the frame id. There are 267 subfolders in the folder data\features\jaad\local_context_c3d_raw_1.5\images, are the frames in these folders the ones that need to generate optical flow files?if not，Would you mind providing a solution?extremely grateful！
