### ISSUE TITLE
Troubles with testing the PCPA and SFRNN model

### ISSUE THREAD

**Issue by MoritzLennartz** [ykotseruba/PedestrianActionBenchmark#19]
Hi,

Thank you very much for your nice work!

I tried to train and test the PCPA and SFRNN model with the provided config_files. 

When I try to test the models, I get the following error: 

![image](https://user-images.githubusercontent.com/64199570/164476670-2eb7dd40-f81c-4581-93eb-3159b0bb311a.png)

can you help me with this?

**Comment by ykotseruba** [comment]
I cannot reproduce this error. Are you using docker?

**Comment by MoritzLennartz** [comment]
yes, i use docker with the dockerfile you provided. 

but i had the same problem with docker as described in issue #14.

The other models in the benchmark work fine with docker.

**Comment by y27choi** [comment]
Hi, I'm also getting the same error when training SFRNN model.  I would love to help reproducing this issue.  Let me know if you need more information on the docker setup.

**Comment by PratikHirapara** [comment]
@MoritzLennartz  did you solve this problem ?
I am getting same error when I am testing PCPA.

ValueError: Data is expected to be in format `x`, `(x,)`, `(x, y)`, or `(x, y, sample_weight)`, found: (array([[[[[18.83785077, 19.85873724, 23.39030612],

**Comment by atanas1054** [comment]
Issue is solved if you set `generator: False` in the config file.
