### ISSUE TITLE
Results without DataGenerator 

### ISSUE THREAD

**Issue by MoritzLennartz** [ykotseruba/PedestrianActionBenchmark#20]
Hello, 

I have a question regarding the usage of the DataGenerator in the PCPA Modell. 

When I use the DataGenerator I get very good results, but a high loss (0,13). When DataGenerator = False the results are very bad, but the loss is very low (0,003). 

DataGenerator = True: 
![image](https://user-images.githubusercontent.com/64199570/167636410-deda9f99-7a84-4452-b6ea-61c28ad82962.png)

DataGenerator = False
![image](https://user-images.githubusercontent.com/64199570/167636484-ade96947-6105-4cd0-b0eb-f96cc5c84ed3.png)

Shouldn't the results be almost identical? What could be the reason for this?

Many greetings
Moritz

**Comment by ykotseruba** [comment]
Hi Moritz, we trained and tested all models with DataGenerator, so I cannot say what could be causing the discrepancy. I'll try to look into it.

**Comment by MoritzLennartz** [comment]
Is the problem perhaps that no global pooling operation for the PCPA Model is performed when Generator = False?

Can you explain to me what exactly the point of the global pooling step is? 

<img width="425" alt="image" src="https://user-images.githubusercontent.com/64199570/168269961-fd131c2e-2237-4715-9032-59e86476acf6.png">


As I understand it, the shape of the local context is [No. Frames, Height, Width, RGB]. Through your global pooling operation every pixel within a frame gets the same RGB values. How can the input be used meaningfully if all pixels have the same colour? 

<img width="403" alt="image" src="https://user-images.githubusercontent.com/64199570/168241278-613945c3-d9f3-4764-885d-e1077f1261fd.png">

**Comment by MoritzLennartz** [comment]
Hi, 

I have trained the PCPA model without the local context and get almost as good results as you published in your paper.  

Maybe you could check again if the local context is processed correctly.

![image](https://user-images.githubusercontent.com/64199570/168800993-3d55468e-4908-4d03-b57b-c94669b3386d.png)

**Comment by ykotseruba** [comment]
Pooling should be performed if `self.process` is set to True. If no generator is used, then processing is done in the `action_predict.py:load_images_crop_and_process()`, otherwise it is done in the generator. As to what causes the discrepancy I cannot say since we did not test the model without the generator and it is used by default.
Unfortunately, right now I cannot run the model to verify the global pooling operation, but you might be correct.

**Comment by MoritzLennartz** [comment]
Hello Yulia, 

Thank you for your answer.

Can you also explain to me why the pooling step is executed before the input is processed with the C3d net?
