### ISSUE TITLE
About the PIE dataset

### ISSUE THREAD

**Issue by aoteman233** [ykotseruba/PedestrianActionBenchmark#21]
hi,thanks for your work
When I reproduce the PCPA model, only set01,set02,set03,set04 are generated in the folder data/featrues/pie.Do you know what's causing it?
It seems that the dataset split is not the same as the paper and what you say in issue 8   [https://github.com/ykotseruba/PedestrianActionBenchmark/issues/8#issue-823109452](url)
![屏幕截图 2022-06-14 152820](https://user-images.githubusercontent.com/73416150/173519450-906ff1ef-5e36-46c2-a103-4bb613bc0794.png)

**Comment by ykotseruba** [comment]
The dataset split is the same as in the paper.  Please see lines 85-95 in `pie_data.py` which is used to generate the data. Sets 5 and 6 are part of validation set, which is currently not used. Please uncomment line 100 in `train_test.py` to use the validation set and features will be generated for those sets as well.

**Comment by aoteman233** [comment]
thank you very much
