### ISSUE TITLE
Results Visualization

### ISSUE THREAD

**Issue by aoteman233** [ykotseruba/PedestrianActionBenchmark#22]
Hello，Excuse me，
As shown in your paper, how do you extract a sample of pedestrians crossing or not crossing the street from the dataset and compare it with the results obtained from the model test? The test program is for the entire dataset, how to extract the test results for a certain pedestrian?

**Comment by ykotseruba** [comment]
Hi, to visualize individual pedestrians you can use `test_data` dictionary (in the `test()` function for the model) which has pedestrian ids, bounding boxes, and other relevant information.

**Comment by aoteman233** [comment]
thank you very much
