### ISSUE TITLE
Pedestrians who are already crossing in the past observations

### ISSUE THREAD

**Issue by Marchetz** [ykotseruba/PedestrianActionBenchmark#25]
Hi,
I have noticed that, in some examples, in the 16 past frames, the pedestrian is in the middle of the street and is already crossing. 
Is it correct to have this type of behavior in the examples? I thought that the crossing behavior will happen only in the future frames.
For now, I've seen it in JAAD split. I share some frames.
Maybe I am doing something wrong but I am checking it right before the function train_model.fit() and I didn't modify the rest of the code.
Thank you very much for your time.

![crossing_jaad_first](https://github.com/ykotseruba/PedestrianActionBenchmark/assets/8883748/df7428ec-88c3-4777-a31b-c24cf5c766e3)
![crossing_jaad_second](https://github.com/ykotseruba/PedestrianActionBenchmark/assets/8883748/b25c33db-8afc-4a7f-9ae5-9317e456352d)

**Comment by ykotseruba** [comment]
Hi @Marchetz, thank you for pointing out this error. Could you please provide video id for the frames you posted?

**Comment by Marchetz** [comment]
Hi @ykotseruba, thank you for the prompt reply.
frames above: video 0143, ped_id 0_143_879b, past frames: 00222 - 00237
frames below: video 0138, ped_id, past_frames: 0_138_854b, past frames: 00193 - 00208.

Let me know if you observe the same thing too.
Thank you very much.

**Comment by ykotseruba** [comment]
Because JAAD videos are cropped, some pedestrians do not have observations pre-crossing, so for these cases frames during crossing are used.

**Comment by Marchetz** [comment]
Ok, now I understand. Thank you very much for this explanation!

**Comment by ykotseruba** [comment]
Closing the issue since it appears to be resolved
