### ISSUE TITLE
code of PedFormer

### ISSUE THREAD

**Issue by lcs1027** [ykotseruba/PedestrianActionBenchmark#26]
Hello, Iuliia
     I am a newly enrolled graduate student from China, and I am very interested in your research direction. You have done quite excellent work. Recently, I have been reading your paper "PedFormer: Pedestrian Behavior Prediction via Cross-Modal Attention Modulation and Gated Multitask Learning." I am very eager to implement this work, but unfortunately, I was not successful. Could you please provide the source code for me? Thank you very much!
changsheng luo

**Comment by ykotseruba** [comment]
Hi, thank you for interest in our work. Unfortunately, we cannot release the code for PedFormer.
