### ISSUE TITLE
file request

### ISSUE THREAD

**Issue by Jason408** [ykotseruba/PedestrianActionBenchmark#30]
Hi, the pkl files for pose_set03 and pose_set04 in the data/features/pie/poses folder are corrupted, and it says pickle data was truncated when loading. can you please provide usable pkl files? Thanks a lot!

**Comment by ykotseruba** [comment]
Hi @Jason408, I was able to download and open both files. Tested with Python versions 3.8, 3.10, 3.11 on Ubuntu 22.04 and Mac OS 14.4. The error you mention can happen when files are not downloaded fully. Can you try downloading them again?

**Comment by Jason408** [comment]
The problem has been resolved, thank you very much!

**Comment by ykotseruba** [comment]
Great, glad to hear it's been resolved! Will close the issue now.
