### ISSUE TITLE
C3D crashing on model download

### ISSUE THREAD

**Issue by dschoerk** [ykotseruba/PedestrianActionBenchmark#5]
command: python3 train_test.py -c ./config_files/C3D.yaml
error: https://i.imgur.com/hkFfpJS.png

running C3D crashes when downloading the model in line https://github.com/ykotseruba/PedestrianActionBenchmark/blob/main/action_predict.py#L1178 because the "weights" folder does not exist. 

a possible solution would be `os.makedirs(os.path.dirname(self._weights), exist_ok=True)` before that line.

**Comment by ykotseruba** [comment]
Thank you for reporting the issue, it is fixed now.
