### ISSUE TITLE
About PIE dataset split

### ISSUE THREAD

**Issue by d-zh** [ykotseruba/PedestrianActionBenchmark#8]
Hi,

In your paper, I find this sentence:

"In the PIE dataset, we follow the data split defined in [42]: videos from set01, set02 and set06 are used for training, set04 and set05 for validation and set03 for testing. The number of pedestrian tracks in PIE is 880, 243 and 719 in train, validation and test sets."

After running codes, the PIE dataset split is different from the paper. Videos from set01, set02 and set04 are used for training, set05 and set06 for validation and set03 for testing. But the number of pedestrian is consistent. Finally, I find these codes in pie_data.py. 
```
    def _get_image_set_ids(self, image_set):
        """
        Returns default image set ids
        :param image_set: Image set split
        :return: Set ids of the image set
        """
        image_set_nums = {'train': ['set01', 'set02', 'set04'],
                          'val': ['set05', 'set06'],
                          'test': ['set03'],
                          'all': ['set01', 'set02', 'set03',
                                  'set04', 'set05', 'set06']}
        return image_set_nums[image_set]
```

Do I understand correctly? Could you tell me which PIE dataset split is correct?

Thanks a lot!

**Comment by ykotseruba** [comment]
It is a typo. We are using pie_data.py to generate the samples for the benchmark, so set06 is used for validation.

**Comment by d-zh** [comment]
Thank you very much!
